translations = {
    "en": {
        "login": "Login",
        "logout": "Logout",
        "display_name": "Display name",
        "username": "Username",
        "password": "Password",
        "language": "Language",
        "dashboard": "Dashboard",
        "tasks": "Tasks",
        "users": "Users",
        "add_task": "Add Task",
        "edit_task": "Edit Task",
        "delete_task": "Delete Task",
        "description": "Description",
        "assigned_user": "Assigned User",
        "priority": "Priority",
        "due_date": "Due Date",
        "pinned": "Pinned",
        "high": "High",
        "medium": "Medium",
        "low": "Low",
        "none": "None",
        "filter_by_user": "Filter by User",
        "filter_by_priority": "Filter by Priority",
        "filter_by_due_date": "Filter by Due Date",
        "sort_by": "Sort by",
        "add_user": "Add User",
        "edit_user": "Edit User",
        "delete_user": "Delete User",
        "role": "Role",
        "admin": "Admin",
        "user": "User",
        "actions": "Actions",
        "save": "Save",
        "cancel": "Cancel",
        "main_info": "Welcome to the Todo List Dashboard. Please log in to continue.",
        "login_failed": "Invalid username or password.",
        "task_created": "Task created successfully.",
        "task_updated": "Task updated successfully.",
        "task_deleted": "Task deleted successfully.",
        "user_created": "User created successfully.",
        "user_deleted": "User deleted successfully.",
        "not_authorized": "You are not authorized to perform this action.",
        "logged_in_as": "Logged in as"
    },
    "pl": {
        "login": "Zaloguj się",
        "logout": "Wyloguj się",
        "display_name": "Nazwa wyświetlana",
        "username": "Nazwa użytkownika",
        "password": "Hasło",
        "language": "Język",
        "dashboard": "Panel główny",
        "tasks": "Zadania",
        "users": "Użytkownicy",
        "add_task": "Dodaj zadanie",
        "edit_task": "Edytuj zadanie",
        "delete_task": "Usuń zadanie",
        "description": "Opis",
        "assigned_user": "Przypisany użytkownik",
        "priority": "Priorytet",
        "due_date": "Termin wykonania",
        "pinned": "Przypięte",
        "high": "Wysoki",
        "medium": "Średni",
        "low": "Niski",
        "none": "Brak",
        "filter_by_user": "Filtruj po użytkowniku",
        "filter_by_priority": "Filtruj po priorytecie",
        "filter_by_due_date": "Filtruj po terminie wykonania",
        "sort_by": "Sortuj według",
        "add_user": "Dodaj użytkownika",
        "edit_user": "Edytuj użytkownika",
        "delete_user": "Usuń użytkownika",
        "role": "Rola",
        "admin": "Administrator",
        "user": "Użytkownik",
        "actions": "Akcje",
        "save": "Zapisz",
        "cancel": "Anuluj",
        "main_info": "Witamy w panelu zadań. Zaloguj się, aby kontynuować.",
        "login_failed": "Nieprawidłowa nazwa użytkownika lub hasło.",
        "task_created": "Zadanie zostało utworzone.",
        "task_updated": "Zadanie zostało zaktualizowane.",
        "task_deleted": "Zadanie zostało usunięte.",
        "user_created": "Użytkownik został utworzony.",
        "user_deleted": "Użytkownik został usunięty.",
        "not_authorized": "Nie masz uprawnień do wykonania tej akcji.",
        "logged_in_as": "Zalogowany jako"
    }
}


def translate(key, lang):
    return translations.get(lang, translations["en"]).get(key, key)
